### ISSUE TITLE
gulp-bower requires bower@'latest' but will load bower which is version 1.3.12

### ISSUE THREAD

**Issue by sochka** [zont/gulp-bower#20]
Hi,
I think it's wrong to use "latest" as version spec in your package json. Because of that I get the following warning if I use your package:
`
npm WARN unmet dependency /home/oleksandr/Projects/wdc/src/main/webapp/node_modules/gulp-bower requires bower@'latest' but will load
npm WARN unmet dependency /home/oleksandr/Projects/wdc/src/main/webapp/node_modules/bower,
npm WARN unmet dependency which is version 1.3.12
`

Even though bower 1.3.12 is the latest bower version. I think you should use 
`'bower': '*'` in `package.json`

**Comment by zont** [comment]
Fixed in #25
