### ISSUE TITLE
gulp-bower brakes because "walk" added braking changes to their code

### ISSUE THREAD

**Issue by Karl-Gustav** [zont/gulp-bower#27]
gulp-bower stopped working for us because the package "walk" just had a breaking change in the way that walk parses directories. I.e. you now need to add directory: 'bower_components' in the gulp-bower config because walk breaks on the "." in the default directory: './bower_components'.

To specify, our gulpfile looks like this: 
```
gulp.task('bower', function () {
    return $.bower({
        cwd: sourceDir
    }).pipe(gulp.dest(sourceDir));
})
````
And in the new version of "walk" this causes this error: "Error: Missing error message". Not very helpful I know, but with some debugging we pinpointed the new version of "walk" as the culprit. Many people rely on "gulp-bower" in their code bases and it's really frustrating to have a build that builds OK then to crash in the very next build with no changes.

We would really like for you to lock down the versions you're using in your package.json file so this doesn't happen again.

We have made a merge request with the changes we need: https://github.com/zont/gulp-bower/pull/25

**Comment by Karl-Gustav** [comment]
We have created a new version of gulp-bower that fixes this problem: https://www.npmjs.com/package/gulp-bower2

Feel free to use this while we wait for the original author to fix this problem.

**Comment by karlvr** [comment]
I've encountered the same issue. Adding `{ 'directory': 'bower_components' }` fixes it for me for the moment. Thanks for the tip.

(I am also specifying a `cwd`)

**Comment by zont** [comment]
#25 merged

**Comment by Karl-Gustav** [comment]
Thanks for fixing this! I'll deprecate gulp-bower2 as soon as #28 is fixed:-)
