### ISSUE TITLE
gulp-bower filles up the "cwd" folder with bower dependencies

### ISSUE THREAD

**Issue by Karl-Gustav** [zont/gulp-bower#28]
gulp-bower filles up the "cwd" folder with bower dependencies (i.e. it doesn't use the "bower_components" folder)

This error exists both in version 0.0.8 and 0.0.9.

**Comment by Karl-Gustav** [comment]
1a816a129e5b1e28909731c32ce3c0af92dbb65d didn't fix the issue:-S My `source/` dir is still full of bower dependencies...

**Comment by zont** [comment]
```
gulp.task('bower', function () {
    return $.bower({
        cwd: 'source/'
    }).pipe(gulp.dest('source/'));
});
```
1) bower work directory is 'source/'
2) bower path name in which installed components is 'bower_components'. Full path is 'source/bower_components'
3) bower load all dependencies in 'source/bower_components'
4) after all loaded gulp-bower create stream and send all loaded data from 'source/bower_components' to it
5) you pipe stream and out all data to 'source/'

It is not a bug.

**Comment by Karl-Gustav** [comment]
It might not be a bug but at the very least it's a change in behavior. Because the setup we have in gulp was the way you had to write it in gulp-bower < 0.0.8

**Comment by Karl-Gustav** [comment]
Or to be more specific the `.pipe(gulp.dest('source/'))` had no effect in gulp-bower < 0.0.8

**Comment by zont** [comment]
You cannot correct check this behavior on old versions because they has incorrect dependency of latest 'walk'

**Comment by Karl-Gustav** [comment]
That's easy to test, just use `gulp-bower2` since that is how your codebase looked before 0.0.8, with the only difference being a fixed working version of walk...

But it doesn't matter, I have removed `.pipe(gulp.dest('source/'))` from our gulpfile.js and now everything works:-)
