### ISSUE TITLE
Support for 'exportsOverride' ala grunt-bower-task

### ISSUE THREAD

**Issue by ctolkien** [zont/gulp-bower#30]
Details:
https://github.com/yatskevich/grunt-bower-task#advanced-usage

**Comment by cherrydev** [comment]
Yup, it's basically impossible to re-create the same functionality of the "exportsOverride" using gulp-bower together with main-bower-files since there is no way of configuring the desired destination directory directly in your bower.json file.  On the other hand, I think that this should probably end up as functionality of main-bower-files instead of including it in gulp-bower.

**Comment by ctolkien** [comment]
Bower does support the `ignore`  property that package authors can use to exclude certain files, but we find that it doesn't really go far enough. jQuery for instance, ignores a bunch of stuff:
https://github.com/jquery/jquery/blob/master/bower.json#L6

But it still includes the entire '/src' folder, when we really only want what's in the '/dist' filter. jQuery itself, the minified version and the source map.

I don't have an answer for any of this, it's just a pain in the butt though :)

**Comment by cherrydev** [comment]
It looks like main-bower-files does about 75% of this right now, except that it does not allow you to associate a destination path with each file pattern, like gulp-bower does.
https://github.com/ck86/main-bower-files/issues/62
I've opened this issue there, but it's uncertain if there's interest from the developer in having this functionality in main-bower-files.

**Comment by niftylettuce** [comment]
:+1: can we plz get this in!

**Comment by aluanhaddad** [comment]
I would really l appreciate it if this functionality were available. I prefer Gulp to Grunt but the convenience of grunt-bower-task is hard to give up.

**Comment by jpdevries** [comment]
+1

**Comment by ErikSchierboom** [comment]
+1

**Comment by jozefizso** [comment]
:+1:

**Comment by yuxiaomin** [comment]
+1

**Comment by toleabivol** [comment]
+1
