### ISSUE TITLE
cmd extra parameters

### ISSUE THREAD

**Issue by boogerlad** [zont/gulp-bower#32]
```
TypeError: Cannot read property 'apply' of undefined
    at Object.module.exports (/root/cutequickposweb/node_modules/gulp-bower/index.js:51:21)
```

when I do `bower({ cmd: 'install --allow-root'})`

**Comment by jmullo** [comment]
Noticed the same. I need to run:

```bower({ cmd: "cache clean" })```

**Comment by joshbrayman** [comment]
From what I can see of [index.js](https://github.com/zont/gulp-bower/blob/master/index.js), it looks like the intention is to call the arguments separately, e.g., bower({cmd: 'install'},['--allow-root']).  However, in running bower({cmd: 'link'}, ['some_local_package', 'some_local_package']) I had to comment out line 46 to get everything to run properly.

**Comment by vjpr** [comment]
+1

**Comment by Grsmto** [comment]
For anyone wanting to apply joshbrayman fix, I had to to this way: `bower({ cmd: 'update'},[['my-module']])` to do a `bower update my-module`.

**Comment by dgreene1** [comment]
maybe... someone could update the readme with this functionality?
