### ISSUE TITLE
bower install --force

### ISSUE THREAD

**Issue by poloagustin** [zont/gulp-bower#52]
Could you please provide an example using the --force option on an install command?

I tried 
```
gulp.task('bower', function () {
    return bower({ directory: 'wwwroot/lib', force: true });
});
```

and

```
gulp.task('bower', function () {
    return bower({ directory:  'wwwroot/lib', cmd: 'install --force' });
});
```

with no effect

**Comment by crazy-genius** [comment]
As write on https://github.com/zont/gulp-bower/blob/master/index.js, 53

function gulpBower(opts, cmdArguments) {}

you shuld write something like 

gulp.task('myTskName', function() {
    return bower({}, '--force');
});

**Comment by amitse** [comment]
I don't think it's working anymore.

**Comment by kcmr** [comment]
The right command name is ["--force-latest" or its alias "-F"](https://bower.io/docs/api/#install-options). Anyway, doesn't seems to work.
